GET  https://localhost:7129/api/Dashborad
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MmZmMjJmZS1mY2QyLTQ3ZDUtOGQyOC1mMGIzYjJkMmFiZTMiLCJnaXZlbl9uYW1lIjoiQWxleCIsImZhbWlseV9uYW1lIjoiTXN0ZXIiLCJqdGkiOiJkZjU3OTI5Ni1mOTAyLTQwMWMtYjA5My1jYjM3MGYwM2UzYTciLCJleHAiOjE2NjE5NjM3MTYsImlzcyI6Imp3dC1Jc3N1ZXMiLCJhdWQiOiJqd3QtQXVkaWVuY2UifQ.I8QrRxf6zx_0WzKmIYNzYLJC-qbHQ0aEMsVvFlneh-o
